# Welcome to Jekyll
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Golf Lounge 18
email: info@golflounge18.com
description: > # this means to ignore newlines until "baseurl:"
  A premier Golfing facility at Sportsplex at 85 Mill Plain Rd, Fairfield, CT 06824
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social
twitter:       golflounge18
facebook:      golflounge18
instagram:     golflounge18
gmap:          Fz94DRLaLfT2

location:      85 Mill Plain Rd, Fairfield, CT 06824
phone:         203-307-5354
email:         info@golflounge18.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/older:num"

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, .idea]
